### ISSUE TITLE
Allow collector to read data ranges from ext

### ISSUE THREAD

**Issue by glaucouri** [glaucouri/XLtoy#14]
Idea here is to read all ranges informations from an external file.
The purpose is to remove the phase of storing working area **inside** the sheet itself. If this will be possible, we can run entire process using only command line
Something like:

```
labels_1:
    type: label
    sheet: sheet1
    range: b23:b43

input_raw_data:
    type: data
    sheet: sheet3
    range: F34:J158

```
